import type { User } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "carlos@techcorp.com.br",
    name: "Carlos Silva",
    phone: "+5511999887766",
    company: "TechCorp Brasil",
    position: "CEO",
    industry: "Tecnologia",
    interests: ["IA", "Startups", "Investimentos", "SaaS"],
    bio: "Empreendedor serial com 15 anos de experiência em tecnologia. Busco parcerias estratégicas e investidores.",
    avatar: "/professional-ceo.png",
    location: { city: "São Paulo", country: "Brasil" },
    lookingFor: ["Investidores", "Co-fundadores", "Parcerias"],
    isOnline: true,
    lastActive: new Date(),
  },
  {
    id: "2",
    email: "ana@financeplus.com.br",
    name: "Ana Rodrigues",
    phone: "+5511988776655",
    company: "FinancePlus",
    position: "CFO",
    industry: "Finanças",
    interests: ["Fintech", "Investimentos", "M&A", "Venture Capital"],
    bio: "CFO com experiência em fusões e aquisições. Especialista em valuation de startups.",
    avatar: "/professional-woman-cfo-finance.jpg",
    location: { city: "São Paulo", country: "Brasil" },
    lookingFor: ["Startups para investir", "Networking", "Parcerias"],
    isOnline: true,
    lastActive: new Date(),
  },
  {
    id: "3",
    email: "roberto@inovaconsult.com.br",
    name: "Roberto Mendes",
    phone: "+5521977665544",
    company: "InovaConsult",
    position: "Diretor de Inovação",
    industry: "Consultoria",
    interests: ["Transformação Digital", "Inovação", "Agile", "Design Thinking"],
    bio: "Ajudo empresas tradicionais a se transformarem digitalmente. 10+ anos de experiência em consultoria.",
    avatar: "/professional-man-consultant-innovation.jpg",
    location: { city: "Rio de Janeiro", country: "Brasil" },
    lookingFor: ["Clientes", "Parcerias", "Palestrantes"],
    isOnline: false,
    lastActive: new Date(Date.now() - 3600000),
  },
  {
    id: "4",
    email: "juliana@healthtech.com.br",
    name: "Juliana Costa",
    phone: "+5531966554433",
    company: "HealthTech Solutions",
    position: "Founder & CTO",
    industry: "HealthTech",
    interests: ["Saúde Digital", "IA em Saúde", "Telemedicina", "Wearables"],
    bio: "Fundadora de startup de saúde digital. Médica e engenheira de software.",
    avatar: "/professional-woman-doctor-tech-founder.jpg",
    location: { city: "Belo Horizonte", country: "Brasil" },
    lookingFor: ["Investidores", "Parcerias Hospitalares", "Desenvolvedores"],
    isOnline: true,
    lastActive: new Date(),
  },
  {
    id: "5",
    email: "pedro@marketingpro.com.br",
    name: "Pedro Santos",
    phone: "+5548955443322",
    company: "MarketingPro Agency",
    position: "Head of Growth",
    industry: "Marketing Digital",
    interests: ["Growth Hacking", "SEO", "Performance", "Branding"],
    bio: "Especialista em crescimento de startups. Já ajudei +50 empresas a escalar.",
    avatar: "/professional-man-marketing-growth.jpg",
    location: { city: "Florianópolis", country: "Brasil" },
    lookingFor: ["Clientes B2B", "Parcerias", "Mentoria"],
    isOnline: true,
    lastActive: new Date(),
  },
  {
    id: "6",
    email: "maria@legaltech.com.br",
    name: "Maria Fernandes",
    phone: "+5541944332211",
    company: "LegalTech Brasil",
    position: "CEO",
    industry: "LegalTech",
    interests: ["Direito Digital", "Compliance", "LGPD", "Contratos Inteligentes"],
    bio: "Advogada e empreendedora. Democratizando o acesso a serviços jurídicos através da tecnologia.",
    avatar: "/professional-woman-lawyer-tech-ceo.jpg",
    location: { city: "Curitiba", country: "Brasil" },
    lookingFor: ["Investidores", "Parcerias com Escritórios", "Desenvolvedores"],
    isOnline: false,
    lastActive: new Date(Date.now() - 7200000),
  },
]
